source_path: # 需要进行合并的文件路径列表
  - /cpfs01/shared/filtered_data/short_sleeve/demo_A_full_process/v2-2/1027_21_205_v2-2_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/demo_A_full_process/v2-2/1031_21_251_v2-2_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/demo_A_full_process/v2-2/1101_21_68_v2-2_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/demo_A_full_process/v2-2/1029_21_244_v2-2_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/demo_A_full_process/v2-2/1101_21_78_v2-2_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/demo_A_full_process/v2-2/1028_21_200_v2-2_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/demo_A_full_process/v2-2/1030_21_271_v2-2_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/demo_A_full_process/v2/1030_21_196_v2_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/demo_A_full_process/v2/1027_20_240_v2_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/demo_A_full_process/v2/1023_21_422_v2_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/demo_A_full_process/v2/1029_21_207_v2_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/demo_A_full_process/v2/1030_20_270_v2_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/demo_A_full_process/v2/1024_20_320_v2_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/demo_A_full_process/v2/1028_20_252_v2_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/demo_A_full_process/v2/1025_21_451_v2_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/demo_A_full_process/v2/1027_21_201_v2_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/demo_A_full_process/v2/1029_20_258_v2_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/demo_A_full_process/v2/1023_20_400_v2_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/demo_A_full_process/v2/1024_21_460_v2_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/demo_A_full_process/v2/1028_21_259_v2_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_A_full_process/v2-1/1029_20_376_v2-1_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_A_full_process/v2-1/1028_20_310_v2-1_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_A_full_process/v2-1/1030_20_400_v2-1_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_A_full_process/v2-1/1027_20_126_v2-1_3000_lerobot
# 合并后数据保存路径
dst_path: /cpfs01/shared/filtered_data/merge_data/open_data/demo_A_full_process/v2-2_0116/
tasks:  
combine_task:
# 任务描述，若无，留空
task_description:
save_method: cv # 视频保存方法，cv或av

# 处理进程数,处理视频部分进程数目，实际进程数为process_count + 3，
#多出的三个进程，分别为data_parquet_processor、episode_stats_processor和log进程
# 如果为None，则使用cpu数；如果非空，则使用给定进程数
process_count: 14