source_path: # 需要进行合并的文件路径列表
  # - /cpfs01/shared/filtered_data/short_sleeve/flatten_fold/v9-3/1022_20_590_v9-3_2000_lerobot
  # - /cpfs01/shared/filtered_data/short_sleeve/flatten_fold/v9-3/1023_27_311_v9-3_3000_lerobot
  # - /cpfs01/shared/filtered_data/short_sleeve/flatten_fold/v9-3/1024_27_433_v9-3_3000_lerobot
  # - /cpfs01/shared/filtered_data/short_sleeve/flatten_fold/v9-3/1005_20_100_v9-1_2000_lerobot
  # - /cpfs01/shared/filtered_data/short_sleeve/flatten_fold/v9-3/1020_27_442_v9-3_3000_lerobot
  # - /cpfs01/shared/filtered_data/short_sleeve/flatten_fold/v9-3/1014_27_170_v9-3_3000_lerobot
  # - /cpfs01/shared/filtered_data/short_sleeve/flatten_fold/v9-3/1022_27_210_v9-3_3000_lerobot
  # - /cpfs01/shared/filtered_data/short_sleeve/flatten_fold/v9-3/1025_27_480_v9-3_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/flatten_fold/v9-3/1009_20_7_v9-1_2000_lerobot
  # - /cpfs01/shared/filtered_data/short_sleeve/flatten_fold/v9-3/1009_21_345_v9-1_3000_lerobot
  # - /cpfs01/shared/filtered_data/short_sleeve/flatten_fold/v9-3/1015_27_140_v9-1_3000_lerobot
  # - /cpfs01/shared/filtered_data/short_sleeve/flatten_fold/v9-3/1007_21_270_v9-1_3000_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve/flatten_fold/v9-3/1013_27_85_v9-1_3000_lerobot
  # - /cpfs01/shared/filtered_data/short_sleeve/flatten_fold/v9-3/1015_21_0_v9-1_3000_lerobot
  # - /cpfs01/shared/filtered_data/short_sleeve/flatten_fold/v9-3/1015_21_15_v9-1_3000_lerobot
  # - /cpfs01/shared/filtered_data/short_sleeve/flatten_fold/v9-3/1016_27_151_v9-1_3000_lerobot
  # - /cpfs01/shared/filtered_data/short_sleeve/flatten_fold/v9-3/1017_27_430_v9-1_3000_lerobot
  # - /cpfs01/shared/filtered_data/short_sleeve/flatten_fold/v9-3/1008_21_282_v9-1_3000_lerobot
  # - /cpfs01/shared/filtered_data/short_sleeve/flatten_fold/v9-3/1010_21_150_v9-1_3000_lerobot
  # - /cpfs01/shared/filtered_data/short_sleeve/flatten_fold/v9-3/1014_21_129_v9-1_3000_lerobot
# 合并后数据保存路径
# dst_path: /cpfs01/shared/filtered_data/merge_data/short_sleeve/flatten_fold/v9-3_0109_repaired/
dst_path: /cpfs01/user/baidexiang/test_data/short_sleeve/flatten_fold/v9-3_0112
tasks:  
combine_task:
# 任务描述，若无，留空
task_description:
  v9-3: flat the cloth
  v9-1: flat the cloth
save_method: cv # 视频保存方法，cv或av

# 处理进程数,处理视频部分进程数目，实际进程数为process_count + 3，
#多出的三个进程，分别为data_parquet_processor、episode_stats_processor和log进程
# 如果为None，则使用cpu数；如果非空，则使用给定进程数
process_count: 5