source_path: # 需要进行合并的文件路径列表
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v1_260129_001_night_shift_101_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v1_260130_001_day_shift_261_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v1_260130_001_night_shift_223_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v1_260130_002_night_shift_170_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v1_260131_001_day_shift_151_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v1_260201_001_day_shift_142_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v1_260201_001_night_shift_57_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v1_260201_002_day_shift_132_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v1_260201_002_night_shift_211_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v1_260202_001_day_shift_242_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v1_260202_002_night_shift_90_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v1_260203_001_day_shift_268_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v2_260209_002_day_shift_204_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v2_260211_002_day_shift_307_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v3_260206_003_day_shift_85_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v3_260209_003_day_shift_210_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v3_260210_003_day_shift_306_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v3_260211_003_day_shift_308_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v4_260206_004_day_shift_200_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v4_260209_004_day_shift_300_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v4_260210_004_day_shift_300_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v4_260211_004_day_shift_301_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v5_260225_002_day_shift_255_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v6_260212_003_day_shift_315_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v6_260213_003_day_shift_316_10000_lerobot
  - /cpfs01/shared/kai05_data/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao/v6_260225_003_day_shift_312_10000_lerobot
# 合并后数据保存路径
dst_path: /cpfs01/shared/kai05_data_train/agilex/flatten_fold/short_sleeve/flatten_fold_weitiao_all_0227
tasks:  
combine_task:
# 任务描述，若无，留空
task_description:
save_method: cv # 视频保存方法，cv或av

# 处理进程数,处理视频部分进程数目，实际进程数为process_count + 3，
# 多出的三个进程，分别为data_parquet_processor、episode_stats_processor和log进程
# 如果为None，则使用cpu数；如果非空，则使用给定进程数
process_count: null