source_path: # 需要进行合并的文件路径列表
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-6/1101_195_391_v6-6_1500_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-6/1030_195_386_v6-6_1500_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-6/1104_195_437_v6-6_1500_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-6/1102_195_411_v6-6_1500_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-6/1103_195_412_v6-6_1500_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-6/1031_195_385_v6-6_1500_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-5/1109_206_530_v6-5_1500_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-5/1030_53_384_v6-5_1500_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-5/1107_171_666_v6-5_1500_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-5/1105_171_391_v6-5_1500_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-5/1108_206_221_v6-5_1500_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-5/1108_206_223_v6-5_1500_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-5/1106_171_180_v6-5_1500_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-5/1104_171_352_v6-5_1500_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-5/1106_171_216_v6-5_1500_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-5/1103_53_385_v6-5_1500_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-5/1111_206_407_v6-5_1500_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-5/1102_53_171_v6-5_1500_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-5/1102_53_383_v6-5_1500_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-5/1110_206_413_v6-5_1500_lerobot
  - /cpfs01/shared/filtered_data/short_sleeve_shirt/demo_B_full_process/v6-5/1031_53_395_v6-5_1500_lerobot
# 合并后数据保存路径
dst_path: /cpfs01/shared/filtered_data/merge_data/open_data/demo_B_full_process/v2-2_0116/
tasks:  
combine_task:
# 任务描述，若无，留空
task_description:
save_method: cv # 视频保存方法，cv或av

# 处理进程数,处理视频部分进程数目，实际进程数为process_count + 3，
#多出的三个进程，分别为data_parquet_processor、episode_stats_processor和log进程
# 如果为None，则使用cpu数；如果非空，则使用给定进程数
process_count: 14